name: Build Kernel Otomatis

on:
  workflow_dispatch:

jobs:
  kernel-compile:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Source Kernel
        uses: actions/checkout@v4

      - name: Inspect Current KernelSU Integration
        run: |
          echo "===== drivers/kernelsu ====="
          ls -la drivers/kernelsu || true

          echo ""
          echo "===== drivers/Kconfig KSU ====="
          grep -n -C 3 -i "kernelsu\|CONFIG_KSU" drivers/Kconfig || true

          echo ""
          echo "===== drivers/Makefile KSU ====="
          grep -n -C 3 -i "kernelsu" drivers/Makefile || true

          echo ""
          echo "===== defconfig KSU ====="
          grep -n -C 3 -i "CONFIG_KSU\|KPROBE" \
            arch/arm64/configs/a3core_eur_open_defconfig || true

          echo ""
          echo "===== fs/open.c KSU ====="
          grep -n -C 4 -i "ksu_" fs/open.c || true
          
      - name: Ubah Default Shell ke Bash
        run: |
          sudo ln -sf /bin/bash /bin/sh

      # ================================
      # CACHE TOOLCHAIN
      # ================================
      - name: Cache Toolchains
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/toolchain_download
          key: toolchain-ubuntu22-clang-r383902b-gcc-14.3-v1
          restore-keys: |
            toolchain-ubuntu22-

      # ================================
      # CACHE APT
      # ================================
      - name: Cache APT
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apt/archives
          key: apt-ubuntu-22.04-v1
          restore-keys: |
            apt-ubuntu-22.04-

      - name: Install Dependencies Sistem
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            bc \
            bison \
            flex \
            libssl-dev \
            libelf-dev \
            ccache \
            python3-minimal \
            python2 \
            git \
            zip \
            unzip \
            curl \
            wget \
            cpio \
            gcc-aarch64-linux-gnu \
            libncurses-dev \
            libyaml-dev \
            tar

      - name: Eksekusi Kompilasi Kernel
        run: |
          chmod +x b.sh
          ./b.sh

      - name: Upload Hasil Jadi
        uses: actions/upload-artifact@v4
        with:
          name: Hasil-Kernel-Sprd
          path: ${{ github.workspace }}/output_artifacts/*
