name: Build DTBS

on:
  workflow_dispatch:

jobs:
  build-dtbs:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Kernel
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            bc \
            bison \
            flex \
            libssl-dev \
            libelf-dev \
            libyaml-dev \
            pkg-config \
            device-tree-compiler \
            python3 \
            python2 \
            git \
            cpio \
            gcc-aarch64-linux-gnu

      - name: Setup Toolchain
        run: |
          echo "${GITHUB_WORKSPACE}/toolchain/clang-r383902/bin" >> "$GITHUB_PATH"
          echo "${GITHUB_WORKSPACE}/toolchain/aarch64-linux-android-4.9/bin" >> "$GITHUB_PATH"

      - name: Setup Environment
        run: |
          echo "ARCH=arm64" >> "$GITHUB_ENV"
          echo "SUBARCH=arm64" >> "$GITHUB_ENV"
          echo "CLANG_TRIPLE=aarch64-linux-gnu-" >> "$GITHUB_ENV"
          echo "CROSS_COMPILE=aarch64-linux-gnu-" >> "$GITHUB_ENV"

          echo "BSP_BUILD_FAMILY=sharkl3" >> "$GITHUB_ENV"
          echo "BSP_BUILD_ANDROID_OS=y" >> "$GITHUB_ENV"
          echo "BSP_BUILD_DT_OVERLAY=y" >> "$GITHUB_ENV"

          echo "DTC_OVERLAY_TEST_EXT=${GITHUB_WORKSPACE}/tools/mkdtimg/ufdt_apply_overlay" >> "$GITHUB_ENV"
          echo "DTC_OVERLAY_VTS_EXT=${GITHUB_WORKSPACE}/tools/mkdtimg/ufdt_verify_overlay_host" >> "$GITHUB_ENV"

      - name: Check LibYAML
        run: |
          echo "===== LIBYAML ====="
          pkg-config --cflags yaml-0.1
          pkg-config --libs yaml-0.1

      - name: Generate Defconfig
        run: |
          make O=out \
            CC=clang \
            LD=ld.lld \
            BSP_BUILD_DT_OVERLAY=y \
            a3core_eur_open_defconfig

      - name: Clean DTC Objects
        run: |
          rm -rf out/scripts/dtc

      - name: Build DTBS
        run: |
          make -j2 V=1 O=out \
            ARCH=arm64 \
            CC=clang \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-gnu- \
            LD=ld.lld \
            HOSTCC=gcc \
            HOSTLDFLAGS="-lyaml" \
            BSP_BUILD_FAMILY=sharkl3 \
            BSP_BUILD_ANDROID_OS=y \
            BSP_BUILD_DT_OVERLAY=y \
            DTC_OVERLAY_TEST_EXT="${GITHUB_WORKSPACE}/tools/mkdtimg/ufdt_apply_overlay" \
            DTC_OVERLAY_VTS_EXT="${GITHUB_WORKSPACE}/tools/mkdtimg/ufdt_verify_overlay_host" \
            dtbs

      - name: Collect DTBS
        run: |
          mkdir -p output_dtbs

          find out/arch/arm64/boot/dts \
            -type f \
            \( -name "*.dtb" -o -name "*.dtbo" \) \
            -exec cp {} output_dtbs/ \;

          echo "===== DTBS ====="
          find output_dtbs -type f -print

      - name: Upload DTBS
        uses: actions/upload-artifact@v4
        with:
          name: DTBS
          path: output_dtbs/*