name: Build Kernel Otomatis

on:
  workflow_dispatch:

jobs:
  kernel-compile:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Source Kernel
      uses: actions/checkout@v4

    - name: Install Dependencies Sistem
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc bison flex libssl-dev libelf-dev ccache python3-minimal python2 git zip unzip curl wget cpio gcc-aarch64-linux-gnu libncurses-dev libyaml-dev tar

    - name: Eksekusi Kompilasi Kernel
      run: |
        chmod +x b.sh
        ./b.sh

    - name: Upload Hasil Jadi (Artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: Hasil-Kernel-KSU-Sprd
        path: ${{ github.workspace }}/output_artifacts/*
